#docker-compose up -d to run in dettach mode
version: '3'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - 'mynet'
    container_name: myapp_redis
  php:
    build:
      context: .
      dockerfile: DockerfilePHP
    volumes:
      - '.:/www/myapp'
    ports:
      - '9000:9000'
    networks:
      - 'mynet'
    container_name: myapp_php
  web:
    build: .
    depends_on:
      - 'php'
    ports:
      - '8080:80'
    volumes:
      - '.:/www/myapp'
    networks:
      - 'mynet'
    container_name: myapp_web
    
volumes:
  redis_data: {}

networks:
  mynet: {}
    
