#stats
#container run --rm -it --name test-nginx -p 8080:80 nginx
#container run --rm -it -v $PWD:/usr/share/nginx/html --name test-nginx -p 8080:80 nginx
FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /www/myapp
COPY . /www/myapp

LABEL maintainer="Andrew Conti <avc.conti@gmail.com>" \ 
	version="1.0"

CMD ["nginx", "-g", "daemon off;"]